# Generated by Django 3.2 on 2021-06-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id_selfie',
            field=models.ImageField(default='media/query/1.jpg', upload_to='media/query'),
        ),
    ]
