# Generated by Django 3.2 on 2021-06-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
